### ISSUE TITLE
`cargo test` panic on android termux

### ISSUE THREAD

**Issue by mazznoer** [azzamsa/islam#10]
```shell
running 30 tests
test hijri::cal::tests::test_equation_of_time ... ok
test hijri::cal::tests::test_georgian_to_julian ... ok
test hijri::cal::tests::test_hijri_to_julian ... ok
test hijri::cal::tests::test_julian_to_gregorian ... ok
test hijri::cal::tests::test_julian_to_hijri ... ok
test hijri::cal::tests::test_dcos ... ok
test hijri::cal::tests::test_dsin ... ok
test hijri::date::tests::from_gregorian ... ok
test hijri::date::tests::from_gregorian_1 ... ok
test hijri::date::tests::from_julian ... ok
test hijri::date::tests::hijri ... ok
test hijri::date::tests::max_month ... ok
test hijri::date::tests::max_year ... ok
test hijri::date::tests::min_month ... ok
test hijri::date::tests::min_year ... ok
test hijri::date::tests::to_gregorian ... ok
test hijri::date::tests::tomorrow ... ok
test hijri::date::tests::out_of_index_month ... ok
test salah::madhab::tests::hanafi_shadow ... ok
test salah::madhab::tests::shafi_shadow ... ok
test salah::config::tests::default ... ok
test salah::method::tests::configs_for_egyptian ... ok
test salah::method::tests::configs_for_muslim_world_league ... ok
test salah::prayer::tests::prayer_name ... ok
test salah::times::tests::remaining_time ... FAILED
test salah::times::tests::current_prayers ... FAILED
test salah::times::tests::next_prayers ... FAILED
test salah::times::tests::after_midnight ... FAILED
test salah::times::tests::before_midnight ... FAILED
test salah::times::tests::praytimes_jakarta ... FAILED

failures:

---- salah::times::tests::remaining_time stdout ----
thread 'salah::times::tests::remaining_time' panicked at /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiff-0.1.13/src/civil/time.rs:330:13:
invalid hour
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- salah::times::tests::current_prayers stdout ----
thread 'salah::times::tests::current_prayers' panicked at /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiff-0.1.13/src/civil/time.rs:330:13:
invalid hour

---- salah::times::tests::next_prayers stdout ----
thread 'salah::times::tests::next_prayers' panicked at /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiff-0.1.13/src/civil/time.rs:330:13:
invalid hour

---- salah::times::tests::after_midnight stdout ----
thread 'salah::times::tests::after_midnight' panicked at /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiff-0.1.13/src/civil/time.rs:330:13:
invalid hour

---- salah::times::tests::before_midnight stdout ----
thread 'salah::times::tests::before_midnight' panicked at /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiff-0.1.13/src/civil/time.rs:330:13:
invalid hour

---- salah::times::tests::praytimes_jakarta stdout ----
thread 'salah::times::tests::praytimes_jakarta' panicked at /data/data/com.termux/files/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jiff-0.1.13/src/civil/time.rs:330:13:
invalid hour


failures:
    salah::times::tests::after_midnight
    salah::times::tests::before_midnight
    salah::times::tests::current_prayers
    salah::times::tests::next_prayers
    salah::times::tests::praytimes_jakarta
    salah::times::tests::remaining_time

test result: FAILED. 24 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--lib`
```

I don't have any clues how to fix this.

**Comment by azzamsa** [comment]
Sorry, can't reproduce. As all the test pass in various machines on CI https://github.com/azzamsa/islam/actions/runs/10313324060 and local machines. Also, I don't have `termux` to reproduce.

![image](https://github.com/user-attachments/assets/dfb9a805-faf9-4df3-8cb8-f3e485a86473)
